/*
 * generated by Xtext 2.12.0
 */
package org.simolutions.nonmem.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.simolutions.nonmem.NMCtlRuntimeModule
import org.simolutions.nonmem.NMCtlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class NMCtlIdeSetup extends NMCtlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new NMCtlRuntimeModule, new NMCtlIdeModule))
	}
	
}
