/*
 * generated by Xtext 2.12.0
 */
package org.simolutions.nonmem


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NMCtlRuntimeModule extends AbstractNMCtlRuntimeModule {
}
