/*
 * generated by Xtext 2.12.0
 */
package org.simolutions.nonmem


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NMCtlStandaloneSetup extends NMCtlStandaloneSetupGenerated {

	def static void doSetup() {
		new NMCtlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
